title: "PM细胞营养"
description: "德国PM细胞营养知识分享平台"
baseurl: ""
url: "https://timkan6-crypto.github.io"
lang: "zh-CN"

author:
  name: "PM健康团队"
  email: "contact@pm-nutrition.com"

# 添加主题设置
theme: minima

markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 排除不需要的文件
exclude:
  - .gitignore
